--- 
- 
  hosts: test1
  name: "Installing Repository"
  tasks: 
    - 
      name: "Installing Repository and Package"
      yum: 
        name: "https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm"
        state: present
        validate_certs: false
    - 
      name: "Installing Zabbix agent"
      yum: 
        name: zabbix-agent
        state: present
    - 
      copy: 
        src: /etc/ansible/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf
      name: "Copy Zabbix agent configuration for Linux"
    - 
      name: "Start the Zabbix agent"
      service: 
        enabled: true
        name: zabbix-agent
        state: started

